## Settings
title: Profile
owner: "Celeste"
url: "https://d3aths.github.io"
baseurl: ""
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "celeste-quinn@live.nmit.ac.nz"
github: "github.com/d3aths"

statement: "Are you sure you're awake?"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"